version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ai-backend-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ai_backend
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ai-backend-network

  redis:
    image: redis:7.2-alpine
    container_name: ai-backend-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - ai-backend-network

  # Optional: MinIO for S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: ai-backend-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - ai-backend-network

volumes:
  mongodb_data:
  redis_data:
  minio_data:

networks:
  ai-backend-network:
    driver: bridge
